language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-9
    - zlib1g
    - zlib1g-dev
env:
  - CXX=g++-9
install:
  - git submodule sync
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
script:
  - make -j8
